project:
  type: book

# Book Metadata
book:
  title: "Diagnostic and Therapeutic Equipments Lab Report"
  author:
  - name: Karthik M Dani
    id: 1BM22MD022
    
  - name: Kushaal Vijay
    id: 1BM22MD023

  - name: Lakshita Varma
    id: 1BM22MD024
    
  date: "2024-07-17"
  chapters:
    - index.qmd
    - bp_measurement.qmd
    - ecg_measurement.qmd
    - emg_measurement.qmd
    - eeg.qmd
    - audiometry.qmd
    - simulation_ecg.qmd
    - simulation_eeg.qmd
    - simulation_defibrillator.qmd
    - simulation_pacemaker.qmd
    - simulation_hemodialysis_machine.qmd

# Bibliography
bibliography: references.bib

# Table of Contents
toc: true
toc-depth: 1
toc-title: "Table of Contents"

# Formatting Options
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 1
    number-sections: true
    code-fold: true
    css: styles.css
    toc-title: "Table of Contents"
    title-block-banner: true
    link-external-icon: true
    
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 1
    number-sections: true
    geometry: "margin=1in"
    links-as-notes: true
    fontsize: 11pt
    latex-engine: xelatex
    keep-tex: true
  epub:
    toc: true
    toc-depth: 1
    number-sections: true
    cover-image: cover.png
    css: styles.css

# Language and Localization
lang: en

# Execution Options
execute:
  echo: true
  warning: false
  error: false

# Editor
editor: visual

# Accessibility Features
accessibility:
  skip-links: true
  aria-labels: true

# Additional Project-level Configurations
number-sections: true

# Footer
footer: "Quarto"
